# Generated by Django 6.0.2 on 2026-02-28 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrescriptionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('delivery_address', models.TextField(help_text='Where should we deliver the medicines?')),
                ('prescription_file', models.FileField(upload_to='prescriptions/')),
                ('status', models.CharField(choices=[('Pending', 'Pending Review'), ('Invoiced', 'Invoice Sent to Customer'), ('Paid', 'Payment Received'), ('Shipped', 'Order Shipped')], default='Pending', max_length=20)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, help_text='Enter total price after review', max_digits=8, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
