# Generated by Django 6.0.2 on 2026-03-21 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecure', '0005_order_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.CharField(help_text='A short teaser for the homepage', max_length=300)),
                ('content', models.TextField(help_text='The full article text')),
                ('image', models.ImageField(blank=True, null=True, upload_to='articles/')),
                ('published_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
