# Generated by Django 6.0.2 on 2026-03-21 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecure', '0006_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='brand',
            field=models.CharField(default='eCure', help_text='e.g., Tylenol, Pfizer, Bayer', max_length=100),
        ),
    ]
